apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30002
  selector:
    app: keycloak
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:11.0.3
          env:
            - name: KEYCLOAK_USER
              value: "keycloak"
            - name: KEYCLOAK_PASSWORD
              value: "keycloak"
            - name: PROXY_ADDRESS_FORWARDING
              value: "false"
            - name: DB_VENDOR
              value: "mariadb"
            - name: DB_ADDR
              value: "mariadb"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "keycloak"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi