apiVersion: v1
kind: Service
metadata:
  name: keycloak1
  labels:
    app: keycloak1
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30003
  selector:
    app: keycloak1
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak1
  labels:
    app: keycloak1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak1
  template:
    metadata:
      labels:
        app: keycloak1
    spec:
      containers:
        - name: keycloak1
          image: jboss/keycloak:4.0.0.Final
#          image: quay.io/keycloak/keycloak:5.0.0
          env:
            - name: KEYCLOAK_USER
              value: "keycloak"
            - name: KEYCLOAK_PASSWORD
              value: "keycloak"
            - name: PROXY_ADDRESS_FORWARDING
              value: "false"
            - name: DB_VENDOR
              value: "h2"
#              value: "postgres"
#            - name: DB_ADDR
#              value: "postgres"
#            - name: DB_PORT
#              value: "5432"
#            - name: DB_DATABASE
#              value: "public"
#            - name: DB_USER
#              value: "root"
#            - name: DB_PASSWORD
#              value: "root"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi