#spring:
#  main:
#    allow-bean-definition-overriding: true

keycloak:
  realm: sample
  auth-server-url: http://keycloak/auth
  ssl-required: external
  resource: sample-client
#  verify-token-audience: true
  #  public-client: true
#  principal-attribute: preferred_username
  credentials:
    secret: 1bb9b327-d325-4714-aa71-83fc060b46d5
  use-resource-role-mappings: true
  securityConstraints:
    - authRoles: user
      securityCollections:
        - name: protected
        - patterns:
            - /*
  policy-enforcer-config:
    enforcement-mode: ENFORCING
    on-deny-redirect-to: accessDenied