spring:
  main:
    allow-bean-definition-overriding: true

server:
  port: 30103
  servlet:
    context-path: /

keycloak:
  realm: localRealm
  auth-server-url: http://www.example.com/auth
  ssl-required: external
  resource: local-app
  verify-token-audience: true
  #  public-client: true
  principal-attribute: preferred_username
  credentials:
    secret: 80c2693f-e6b0-4489-87d3-cff8bb90ab8f
  use-resource-role-mappings: true
  confidential-port: 0