apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: passta-contest.io
      http:
        paths:
          - path: /
            backend:
              serviceName: common-original-jwt2
              servicePort: 8080
